vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    articles:
      uri_prefix: asset/img/articles
      upload_destination: "%kernel.project_dir%/public/asset/img/articles"
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: Vich\UploaderBundle\Naming\UniqidNamer
